### PR TITLE
added Todo-App created with React

### PR DESCRIPTION
**Pull request by jonasaky**
Using `npm create-react-app` to create a new Todo-App! 
The App is written in pure React, it uses useState, useContext and localStorage. 
The App is able to add items, remove items and reset list of items.
The App has validations to avoid duplicates.
image

## Happy HacktoberFest 2020!

### CODE REVIEW

**Comment by jonasaky** [comment]
@Aju100 , @Rohan-Shakya , would you mind reviewing this? thanks so much in advance!

**Comment by Aju100** [comment]
Hi @jonasaky  there, we will review it. Thank you for your PR

**Comment by Aju100** [comment]
@jonasaky  can you please deploy any web services and share the URL.

**Comment by jonasaky** [comment]
hey there @Aju100 , sure thing, I will deploy it and share the link with you, thanks for reviewing

**Comment by jonasaky** [comment]
@Aju100 , I've just deploy the App, please take a look at: https://basic-todo.netlify.app/

**Comment by Rohan-Shakya** [comment]
@jonasaky Outstanding work!! It would be nice if you put more styling and edit functionality.

**Comment by jonasaky** [comment]
Thank you!

**Comment by Aju100** [comment]
@jonasaky  awesome. thank you for your contributions

**Pull request merged**
