### PR TITLE
Rohan

### PR DESCRIPTION
**Pull request by Rohan-Shakya**
# Beginner Project - Todo App
With Create-React-App

### CODE REVIEW

**Comment by Aju100** [comment]
@Rohan-Shakya  hello there, can you please deploy on any services like netfliy or vercel.

**Comment by Rohan-Shakya** [comment]
sure !!

**Comment by prashantacharya** [comment]
@Rohan-Shakya would be better if you could put the screenshot here and deploy the application on netlify or GH pages.

**Comment by Rohan-Shakya** [comment]
# Facebook-clone UI
> With React
Link
Image
Image2

**Comment by Rohan-Shakya** [comment]
# Facebook-clone UI
> With React
[Link](https://facebook-clone123.netlify.app)
Image
Image2

**Comment by Rohan-Shakya** [comment]
## Link for [Todolist](https://todolist456.netlify.app/)
> https://todolist456.netlify.app/

**Pull request merged**
